# Change prefix from Ctrl+B to Ctrl+A (easier to reach)
set -g prefix C-a
unbind C-b

# Split panes with | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# 256 color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Cursor Settings
set -ga terminal-overrides ',*:Ss=\033[%p1%d q:Se=\033[1 q'

# Increase scrollback buffer
set -g history-limit 10000

# Reload config with prefix+r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Smart pane switching with awareness of Neovim splits.
bind-key -n C-h if -F "#{@pane-is-vim}" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if -F "#{@pane-is-vim}" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if -F "#{@pane-is-vim}" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if -F "#{@pane-is-vim}" 'send-keys C-l' 'select-pane -R'

# Pane swapping with prefix+Arrow
bind-key Left  run-shell 'tmux select-pane -L && tmux swap-pane -s "!" -d'
bind-key Right run-shell 'tmux select-pane -R && tmux swap-pane -s "!" -d'
bind-key Up    run-shell 'tmux select-pane -U && tmux swap-pane -s "!" -d'
bind-key Down  run-shell 'tmux select-pane -D && tmux swap-pane -s "!" -d'

# Smart pane resizing (repeat by holding down Alt+Arrow)
bind-key -n M-Left if -F "#{@pane-is-vim}" 'send-keys M-Left' 'resize-pane -L 3'
bind-key -n M-Right if -F "#{@pane-is-vim}" 'send-keys M-Right' 'resize-pane -R 3'
bind-key -n M-Up if -F "#{@pane-is-vim}" 'send-keys M-Up' 'resize-pane -U 3'
bind-key -n M-Down if -F "#{@pane-is-vim}" 'send-keys M-Down' 'resize-pane -D 3'

# Pane / Split Saving config
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins"

# Inactive window/pane background
set -g window-style 'fg=colour247,bg=colour236'

# Active window/pane background
set -g window-active-style 'fg=colour250,bg=black'

# Border line styles and colors
set -g pane-border-lines double
set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=#ff0011,bold"

# Display current path or pane ID directly on the top border
set -g pane-border-status top
# set -g pane-border-format " #[fg=#ff0011]#P #[fg=white]#{pane_current_path} " # display FULL PATH
set -g pane-border-format " #[fg=#ff0011]#P #[fg=white]#{b:pane_current_path} "

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Restore session on start
set -g @continuum-restore 'on'

if-shell '[ ! -x "$HOME/.config/tmux/plugins/tpm/tpm" ]' \
    'display-message -d 0 "WARNING: tpm is not executable! Run: chmod -R +x ~/.config/tmux/plugins"'

run "$HOME/.config/tmux/plugins/tpm/tpm"
