# Change prefix from Ctrl+B to Ctrl+A (easier to reach)
set -g prefix C-a
unbind C-b

# Split panes with | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"


# Mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# 256 color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Cursor Settings
set -ga terminal-overrides ',*:Ss=\033[%p1%d q:Se=\033[1 q'

# Increase scrollback buffer
set -g history-limit 10000

# Reload config with prefix+r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# '@pane-is-vim' is a pane-local option that is set by the plugin on load,
# and unset when Neovim exits or suspends; note that this means you'll probably
# not want to lazy-load smart-splits.nvim, as the variable won't be set until
# the plugin is loaded

# Smart pane switching with awareness of Neovim splits.
bind-key -n C-h if -F "#{@pane-is-vim}" 'send-keys C-h'  'select-pane -L'
bind-key -n C-j if -F "#{@pane-is-vim}" 'send-keys C-j'  'select-pane -D'
bind-key -n C-k if -F "#{@pane-is-vim}" 'send-keys C-k'  'select-pane -U'
bind-key -n C-l if -F "#{@pane-is-vim}" 'send-keys C-l'  'select-pane -R'

# Alternatively, if you want to disable wrapping when moving in non-neovim panes, use these bindings
# bind-key -n C-h if -F '#{@pane-is-vim}' { send-keys C-h } { if -F '#{pane_at_left}'   '' 'select-pane -L' }
# bind-key -n C-j if -F '#{@pane-is-vim}' { send-keys C-j } { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
# bind-key -n C-k if -F '#{@pane-is-vim}' { send-keys C-k } { if -F '#{pane_at_top}'    '' 'select-pane -U' }
# bind-key -n C-l if -F '#{@pane-is-vim}' { send-keys C-l } { if -F '#{pane_at_right}'  '' 'select-pane -R' }

# Pane swapping with prefix+Arrow.
bind-key Left  swap-pane -s '{left-of}'
bind-key Right swap-pane -s '{right-of}'
bind-key Up    swap-pane -s '{up-of}'
bind-key Down  swap-pane -s '{down-of}'

# Smart pane resizing with awareness of Neovim splits (repeatable with -r).
bind-key -n -r M-Left  if -F "#{@pane-is-vim}" 'send-keys M-Left'  'resize-pane -L 3'
bind-key -n -r M-Right if -F "#{@pane-is-vim}" 'send-keys M-Right' 'resize-pane -R 3'
bind-key -n -r M-Up    if -F "#{@pane-is-vim}" 'send-keys M-Up'    'resize-pane -U 3'
bind-key -n -r M-Down  if -F "#{@pane-is-vim}" 'send-keys M-Down'  'resize-pane -D 3'

# Pane / Split Saving config
# use prefix + Ctrl-s to save
# use prefix + Ctrl-r to restore
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Restore session on start -- disable this option to manually restore
set -g @continuum-restore 'on'

if-shell '[ ! -x "$HOME/.config/tmux/plugins/tpm/tpm" ]' \
    'display-message -d 0 "WARNING: tpm is not executable! Run: chmod -R +x ~/.config/tmux/plugins"'

run "$HOME/.config/tmux/plugins/tpm/tpm"
